# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and contributors.
#
# SPDX-License-Identifier: Apache-2.0
name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21

    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.52.2

    - name: Test
      run: make test
