# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and contributors.
#
# SPDX-License-Identifier: Apache-2.0
name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.26.2'

    - name: Lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.62.2

    - name: Test
      run: make test
